package com.rockspoon.error;

public enum ErrorCode {
  // Addresses API
  AddressNotFoundError,
  AmbiguousAddress,
  IncompleteAddress,
  // User APIs
  AlreadyValidatedError,
  InvalidKeyError,
  InvalidPinError,
  InvalidOldPasswordError,
  InvalidResetMethodError,
  UserAlreadyExistsError,
  UserNotFoundError,
  ValidationMethodError,
  VeryWeakPasswordError,
  InvalidShortPasswordError,
  ShortPasswordAlreadyInUse,
  WrongUsernamePasswordError,
  WrongConfirmationPassword,
  EmployeeDoesNotBelongsToUserError,
  InvalidLedgerEntryType,
  InvalidLedgerEntryAmount,
  InvalidLedgerEntryDate,
  // Removing Owners
  SingleOwnerError,
  // Record Not found in database when searched by id
  RecordNotFoundException,
  FetchHolidayArgumentMissing,
  NotNullError,
  SmsDeliveryError,
  ForbiddenError,
  InternalServerError,
  InvalidArgumentError,
  MissingArgumentError,
  UnknownError,
  DeviceTypeDoesntSupportLocation,
  DeviceTypeDoesntSupportStations,
  DeleteAssignedRoleError,
  DuplicatedRoleError,
  LocationToDeleteContainsDeviceError,
  DestinationEqualsOrigin,

  InternalError,
  AlreadyRegisteredError,
  RegistrationError,

  // Clock-in / clock-out
  AlreadyClockedInError,
  AlreadyClockedOutError,
  AlreadyPausedError,
  AlreadyResumedError,
  InPauseError,
  NotPausedError,
  NotClockedInError,
  NotRunningError,
  InvalidClockSequence,

  // Ordering - Table Setup
  OrderingInvalidSeatNumberError,
  OrderingDiningSectionSpotNotFoundError,
  OrderingDiningSectionSpotNotInVenueError,
  OrderingDiningSectionSpotNotAvailableError,
  OrderingDuplicatedSeatsError,
  OrderingDiningPartyWrongVenueError,
  OrderingUpdateActionNotSupportedError,
  OrderingEmployeeNotAuthorizedError,
  OrderingDiningPartyUpdateConflictError,
  OrderingDinerSessionWrongVenueError,
  OrderingDinerSessionWrongDiningPartyError,
  OrderingCouldNotRemoveDiningSectionSpotsError,
  OrderingOutstandingTabBalanceNotZeroError,
  OrderingNullVenueError,
  OrderingNullEmployeeError,
  OrderingEmptyDiningPartyNameError,
  // Ordering - Cart Management
  OrderingCartItemInstanceNotFoundRemoveError,
  OrderingCartItemInstanceNotPendingRemoveError,
  OrderingCartItemInstanceNotFoundUpdateError,
  OrderingCartItemInstanceWithNoIdUpdateError,
  OrderingCartItemInstanceNotPendingUpdateError,
  OrderingCartOrderItemsEmptyError,
  OrderingCartOrderItemNotFoundUpdateError,
  OrderingCartStatusTransitionNotAllowedError,
  OrderingCartItemNotFoundAddError,
  OrderingCartEmployeeNotFoundAddError,
  OrderingCartCategoryNotFoundAddError,
  OrderingCartOrderItemRepeadAddError,
  OrderingCartItemInstanceComplementaryNonZeroAmountError,
  OrderingCartItemInstanceComplementaryIsPayableOrderItemError,
  OrderingCartItemInstanceNoIsPayableOrderItemError,
  OrderingCartDinerSessionNotFoundInOrderItemError,
  OrderingCartItemInstanceSplitPlateTrueWithSingleOrderItemError,
  OrderingCartOrderItemIsPayableNotFoundError,
  OrderingCartOrderItemDinerSessionNotFoundError,

  // Ordering - Fire
  OrderingFireItemListNullError,
  OrderingFireMissingItemsFiringTypeError,
  OrderingFireMissingDeltaFireTimeError,
  OrderingFireEmptyItemInstanceListError,
  OrderingFireItemInstanceNotFoundError,
  OrderingItemInstanceWrongDiningPartyError,
  OrderingFireItemInstanceNotPendingError,
  // Ordering - Tab Management
  OrderingEmptyInputTabError,
  OrderingTabManagementInvalidState,
  OrderingEmptyTabError,
  OrderingTabItemInstanceNotInDiningPartyError,
  OrderingTabCentsDistributionError,
  OrderingTabUnsuportedItemInstanceStatusError,
  OrderingTabInternalErrorWrongOperationError,
  OrderingTabAmountMismatchError,
  OrderingTabItemInstanceEmptyTabError,
  OrderingTabDuplicatedDinerSessionInTabListError,
  OrderingTabDinerNotInDiningPartyError,
  OrderingTabNullTabEntryAmountError,
  ConnectionError, SSIDNotFoundError, PrintJobCannotBeDoneError, PrintJobInvalidPayloadError, OrderingTabNullTabEntrySplitWeightError

}
